### ISSUE TITLE
The Show instance for L is not good

### ISSUE THREAD

**Issue by athas** [mainland/srcloc#13]
The `Show` instance for the `L` type can result in very hard-to-read output because it does not contain any parentheses.  Given

```
data P a b = P a b deriving (Show)
```

Then

```
> L noLoc (L noLoc () `P` L noLoc ()) `P` L noLoc ()
P P () () ()
> L noLoc () `P` L noLoc (L noLoc () `P` L noLoc ())
P () P () ()
```

This is essentially what happens when you use `L` to wrap every node in an AST.  I don't *think* it's ambiguous, but it is certainly hard to read.  I think the `Show` instance should always wrap the result in parentheses.

**Comment by mainland** [comment]
Try this:

```
instance Show x => Show (L x) where
    showsPrec d (L _ x) = showsPrec d x
```

Is that better? I think that's the correct fix.

**Comment by athas** [comment]
Oh yes, I forgot that `Show` actually has functionality for inserting proper parens.
