### ISSUE TITLE
SrcLoc not a monoid?

### ISSUE THREAD

**Issue by mitchellwrosen** [mainland/srcloc#5]
Just curious, is there a reason why `SrcLoc` does not inherit `Loc`'s Monoid instance?

**Comment by mainland** [comment]
Nope!

**Comment by mitchellwrosen** [comment]
Cool. And... is there any reason `L` isn't a `Functor`? :)

**Comment by mainland** [comment]
Is there any reason you haven't yet submitted a pull request? ;)

**Comment by mitchellwrosen** [comment]
Nope, here ya go https://github.com/mainland/srcloc/pull/6
