### ISSUE TITLE
Pos ordering

### ISSUE THREAD

**Issue by srenatus** [mainland/srcloc#8]
Hi there.

Looking at that:

```console
> let p = startPos "foo.c"
> let q = startPos "bar.c"
> min p q
Pos "bar.c" 1 1 0
>
```

I wonder if [the chosen ordering](https://github.com/mainland/srcloc/blob/master/Data/Loc.hs#L65-L67) isn't a little counter-intuitive. I guess a partial order makes sense here, but I couldn't decide between

- [altfloat's Data.Poset](https://hackage.haskell.org/package/altfloat-0.3.1/docs/Data-Poset.html)
- [order's Data.PartialOrder](https://hackage.haskell.org/package/orders-0.1.0.0/docs/Data-PartialOrder.html)
- [lattices' Algebra.PartialOrd](http://hackage.haskell.org/package/lattices-1.3/docs/Algebra-PartialOrd.html)
- leaving a `undefined` in that Ord instance to explode later.

Any ideas? :) Maybe some hint to fix my intuition?

**Comment by mainland** [comment]
Does the ordering make sense to you in the case where the file names are the same? Hopefully so.

Assuming we want a total order, how would you then order positions in different files? I think the library makes a sensible choice. What do you think is a more sensible total order?

And `Ord` instance that threw an exception would be quite bad, so I don't see that as an option. I am reluctant to pull in another dependency, and as you note, it is not clear which to choose.

**Comment by srenatus** [comment]
> Does the ordering make sense to you in the case where the file names are the same? Hopefully so.

Yep.

> Assuming we want a total order, how would you then order positions in different files? I think the library makes a sensible choice. What do you think is a more sensible total order?

I'm not sure there is one, to be honest. With `p = Pos "a.c" x y` and `q = Pos "b.c" z w`, I'd suppose that `p <= q` iff `(x, y) <= (z, w)` could make sense? As in "one position is smaller than another one if it starts earlier (and if it's the same, ends earlier)". That is, comparing positions without caring for the file name.

What got me wondering initially was the Monoid Loc instance, though. Say, line 1-10, `mappend`ed to line 21-30 gets me line 1-30? Again, alternatives are not obvious... line 1-10 AND 21-30 seems complicated, as one would probably want to mappend 1-10 with 11-20 to 1-20.

Anyway, this is not critical. Since there's no nice way out, let's keep it at that. Glad we talked ;)
